FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY $PROJECT_NAME/*.csproj ./
COPY AppHub/AppHub.csproj /AppHub/
COPY *.config ./
RUN dotnet restore --packages packages

# Copy everything else and build
COPY . .
WORKDIR /app/$PROJECT_NAME
RUN dotnet publish -c Release -o out

# COPY . ./
# RUN dotnet ef migrations add InitialCreate

# COPY . ./
# RUN dotnet ef database update

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app/

COPY --from=build /app/$PROJECT_NAME/out .
ENTRYPOINT ["dotnet", "$PROJECT_NAME.dll"]
