FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /app
ARG project_name
# Copy csproj and restore as distinct layers
COPY $project_name/*.csproj ./
COPY AppHub/AppHub.csproj /AppHub/
COPY *.config ./
RUN dotnet restore --packages packages

# Copy everything else and build
COPY . .
WORKDIR /app/$project_name
RUN dotnet publish -c Release -o out

# COPY . ./
# RUN dotnet ef migrations add InitialCreate

# COPY . ./
# RUN dotnet ef database update

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app/
COPY --from=build /app/$project_name/out .
ENTRYPOINT ["dotnet", "${project_name}.dll"]
